In [2]:
import torch
import numpy as np

1.张量元素类型转换

In [5]:
tensor1=torch.tensor([1,2,3])
print(tensor1.dtype)

torch.int64


In [6]:
tensor1=tensor1.type(torch.float64)
print(tensor1.dtype)

torch.float64


In [7]:
tensor1=tensor1.half()
print(tensor1.dtype)

torch.float16


In [8]:
print(tensor1)

tensor([1., 2., 3.], dtype=torch.float16)


In [9]:
tensor1=tensor1.to(torch.complex64)
print(tensor1,tensor1.dtype)

tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


In [13]:
np.set_printoptions(precision=6)
torch.set_printoptions(precision=6)
#1. tensor->ndarray
tensor1=torch.rand(3,2)
print(tensor1)

tensor([[0.113942, 0.279812],
        [0.065203, 0.568214],
        [0.948960, 0.984235]])


In [14]:
ndarray1=tensor1.numpy()
print(ndarray1)

[[0.113942 0.279812]
 [0.065203 0.568214]
 [0.94896  0.984235]]


In [15]:
tensor1[:,0]=10
print(tensor1)
print(ndarray1)

tensor([[10.000000,  0.279812],
        [10.000000,  0.568214],
        [10.000000,  0.984235]])
[[10.        0.279812]
 [10.        0.568214]
 [10.        0.984235]]


In [16]:
#使用copy方法避免共享内存
ndarray2=tensor1.numpy().copy()
print(ndarray2)

[[10.        0.279812]
 [10.        0.568214]
 [10.        0.984235]]


In [18]:
tensor1[:,0]=5
print(tensor1)
print(ndarray1)
print(ndarray2)

tensor([[5.000000, 0.279812],
        [5.000000, 0.568214],
        [5.000000, 0.984235]])
[[5.       0.279812]
 [5.       0.568214]
 [5.       0.984235]]
[[10.        0.279812]
 [10.        0.568214]
 [10.        0.984235]]


In [20]:
#ndarray->tensor
ndarray1=np.random.randn(3,2)
tensor1=torch.from_numpy(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-0.585787,  1.180051],
        [-0.419932, -0.094847],
        [ 0.656500, -0.128721]], dtype=torch.float64)
[[-0.585787  1.180051]
 [-0.419932 -0.094847]
 [ 0.6565   -0.128721]]


In [26]:
ndarray1[:,0]=5
print(tensor1)
print(ndarray1)

tensor([[ 5.000000,  1.180051],
        [ 5.000000, -0.094847],
        [ 5.000000, -0.128721]], dtype=torch.float64)
[[ 5.        1.180051]
 [ 5.       -0.094847]
 [ 5.       -0.128721]]


In [27]:
#使用copy方法避免共享内存
tensor2=torch.from_numpy(ndarray1.copy())
ndarray1[:,0]=7
print(ndarray1)
print(tensor1)
print(tensor2)

[[ 7.        1.180051]
 [ 7.       -0.094847]
 [ 7.       -0.128721]]
tensor([[ 7.000000,  1.180051],
        [ 7.000000, -0.094847],
        [ 7.000000, -0.128721]], dtype=torch.float64)
tensor([[ 5.000000,  1.180051],
        [ 5.000000, -0.094847],
        [ 5.000000, -0.128721]], dtype=torch.float64)


In [30]:
#使用tensor方法直接转换成Tensor
ndarray1=np.random.rand(3,2)
tensor1=torch.tensor(ndarray1)
print(tensor1)

tensor([[0.859702, 0.626205],
        [0.875163, 0.733482],
        [0.061563, 0.555502]], dtype=torch.float64)


In [33]:
ndarray1[:,0]=5
print(ndarray1)
print(tensor1)

[[5.       0.626205]
 [5.       0.733482]
 [5.       0.555502]]
tensor([[0.859702, 0.626205],
        [0.875163, 0.733482],
        [0.061563, 0.555502]], dtype=torch.float64)


In [34]:
#张量与标量的转换
tensor1=torch.tensor(10)
print(tensor1)

tensor(10)


In [35]:
print(tensor1.item())

10


In [37]:
tensor1=torch.tensor([10])
print(tensor1)
print(tensor1.item())

tensor([10])
10


In [38]:
tensor1=torch.tensor([[10]])
print(tensor1)
print(tensor1.item())

tensor([[10]])
10
