In [1]:
import torch

In [2]:
#1.四则运算
tensor1=torch.randint(low=0,high=10,size=(2,3))
print(tensor1)


tensor([[4, 8, 9],
        [1, 7, 6]])


In [3]:
print(tensor1+10)

tensor([[14, 18, 19],
        [11, 17, 16]])


In [4]:
print(tensor1.add(10))

tensor([[14, 18, 19],
        [11, 17, 16]])


In [5]:
print(tensor1)

tensor([[4, 8, 9],
        [1, 7, 6]])


In [7]:
print(tensor1.add_(10))
print(tensor1)

tensor([[24, 28, 29],
        [21, 27, 26]])
tensor([[24, 28, 29],
        [21, 27, 26]])


In [8]:
print(tensor1.sub_(10))

tensor([[14, 18, 19],
        [11, 17, 16]])


In [9]:
print(tensor1**2)

tensor([[196, 324, 361],
        [121, 289, 256]])


In [11]:
print(tensor1.pow(2))
print(tensor1)

tensor([[196, 324, 361],
        [121, 289, 256]])
tensor([[14, 18, 19],
        [11, 17, 16]])


In [12]:
print(tensor1.pow_(2))
print(tensor1)

tensor([[196, 324, 361],
        [121, 289, 256]])
tensor([[196, 324, 361],
        [121, 289, 256]])


In [13]:
print(tensor1.sqrt())

tensor([[14., 18., 19.],
        [11., 17., 16.]])


In [14]:
print(tensor1)

tensor([[196, 324, 361],
        [121, 289, 256]])


In [16]:
tensor1=tensor1.float()
print(tensor1.sqrt_())
print(tensor1)

tensor([[14., 18., 19.],
        [11., 17., 16.]])
tensor([[14., 18., 19.],
        [11., 17., 16.]])


In [17]:
tensor1=torch.tensor([1.0,2,3])
print(tensor1)
print(2.7182818**tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])


In [18]:
print(tensor1.exp())

tensor([ 2.7183,  7.3891, 20.0855])


In [19]:
print(tensor1)
print(tensor1.exp_())
print(tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [20]:
tensor1=torch.tensor([1.0,2,3])
print(tensor1)
print(tensor1.log())
print(tensor1)
print(tensor1.log_())
print(tensor1)

tensor([1., 2., 3.])
tensor([0.0000, 0.6931, 1.0986])
tensor([1., 2., 3.])
tensor([0.0000, 0.6931, 1.0986])
tensor([0.0000, 0.6931, 1.0986])


In [21]:
#计算张量的哈达玛积
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[1,2],[3,4]])
print(tensor1+tensor2)
print(tensor1*tensor2)

tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [22]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


In [23]:
#矩阵乘法
tensor1=torch.tensor([[1,2,3],[4,5,6]])
tensor2=torch.tensor([[1,2],[3,4],[5,6]])
print(tensor1@tensor2)

tensor([[22, 28],
        [49, 64]])


In [24]:
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])


In [25]:
print(tensor1.mm(tensor2))

tensor([[22, 28],
        [49, 64]])


In [28]:
tensor1=torch.tensor([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
tensor2=torch.tensor([[[1,2],[3,4],[5,6]],[[6,5],[4,3],[2,1]]])
print(tensor1@tensor2)
print(tensor1.matmul(tensor2))


tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [38]:
#验证内存的共享和节省内存
X=torch.randint(low=1,high=10,size=(3,2,4))
print(X)
print(id(X))

tensor([[[6, 1, 5, 8],
         [7, 8, 7, 5]],

        [[4, 1, 1, 9],
         [6, 3, 8, 5]],

        [[1, 4, 6, 5],
         [4, 8, 2, 9]]])
2925039364576


In [39]:
# X=X+10 会开辟新内存空间
X+=10
print(id(X))

2925039364576


In [44]:
X=torch.randint(low=1,high=10,size=(3,2,4))
Y=torch.randint(low=1,high=10,size=(3,4,1))
print(X.shape)
print(id(X))
print(X)
print(Y)
print(X@Y)
# X=X@Y
# X@=Y
X[:]=X@Y
print(X.shape)
print(X)
print(id(X))

torch.Size([3, 2, 4])
2925039334208
tensor([[[5, 4, 3, 8],
         [6, 3, 3, 1]],

        [[6, 5, 3, 3],
         [6, 9, 2, 5]],

        [[9, 3, 5, 5],
         [4, 2, 5, 1]]])
tensor([[[8],
         [4],
         [3],
         [1]],

        [[2],
         [9],
         [8],
         [4]],

        [[2],
         [4],
         [6],
         [1]]])
tensor([[[ 73],
         [ 70]],

        [[ 93],
         [129]],

        [[ 65],
         [ 47]]])
torch.Size([3, 2, 4])
tensor([[[ 73,  73,  73,  73],
         [ 70,  70,  70,  70]],

        [[ 93,  93,  93,  93],
         [129, 129, 129, 129]],

        [[ 65,  65,  65,  65],
         [ 47,  47,  47,  47]]])
2925039334208
