In [1]:
import torch
from torch.nn import MSELoss

In [11]:
#定义数据
x=torch.tensor(10.0)
y=torch.tensor(3.0).unsqueeze(dim=0)
print(x)
print(y)

tensor(10.)
tensor([3.])


In [12]:
#初始化参数
w=torch.rand(1,1,requires_grad=True)
b=torch.rand(1,1,requires_grad=True)

In [13]:
#前向传播，得到输出
z=x*w+b
print(z)

tensor([[6.0372]], grad_fn=<AddBackward0>)


In [14]:
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(y.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [15]:
#计算损失函数
loss=torch.nn.MSELoss()
loss_value=loss(z,y)
print(loss_value)
print(loss_value.is_leaf)

tensor(9.2243, grad_fn=<MseLossBackward0>)
False


In [16]:
#反向传播
loss_value.backward()

In [17]:
print(w.grad)
print(b.grad)

tensor([[60.7430]])
tensor([[6.0743]])
