In [19]:
import torch
import numpy as np
from torch import IntTensor
from torch.onnx.symbolic_opset9 import rand_like

1.基本张量创建
（1）按内容创建张量

In [8]:
tensor1=torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10.)
torch.Size([])
torch.float32


In [14]:
#传入一个一维数组
tensor1=torch.tensor([1.0,2,3])
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([1., 2., 3., 4.])
torch.Size([4])
torch.float32


In [ ]:
#传入一个二维ndarray
tensor2=torch.tensor([1.0,2,3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

In [20]:
#传入一个二维ndarray
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


（2）创建制定形状的张量

In [21]:
tensor1 = torch.Tensor(3,2,4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[-6.0097e-31,  1.9730e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [24]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [25]:
tensor2 = torch.Tensor(np.array([[1, 2, 3, 4], [4, 5, 6, 7]]))
print(tensor2)
print(tensor2.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.float32


In [26]:
tensor1=torch.Tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


（3）创建指定类型的张量

In [27]:
#int(int32)
tensor1=torch.IntTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int64


In [28]:
#int(int64)
tensor1=torch.LongTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [ ]:
#int(int16)
tensor1=torch.ShortTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

In [34]:
#int(int8)
tensor1=torch.ByteTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.uint8)
print(tensor1.dtype)
print(tensor2.dtype)


torch.uint8
torch.uint8
tensor([[ 32,  30,  64],
        [141, 128,   5]], dtype=torch.uint8)


In [36]:
#float类型
tensor1=torch.FloatTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float32
torch.float32
tensor([[1., 2., 3.],
        [4., 4., 5.]])


In [35]:
#double类型
tensor1=torch.DoubleTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float64
torch.float64
tensor([[2.9889e-311,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float64)


In [37]:
#half
tensor1=torch.HalfTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.float16
torch.float16
tensor([[1.5318e-05, 1.5318e-05, 1.5318e-05],
        [2.0000e+00, 0.0000e+00, 2.1250e+00]], dtype=torch.float16)


In [40]:
#bool
tensor1=torch.BoolTensor(2,3)
tensor2=torch.tensor([1,2,3],dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.bool
torch.bool
tensor([[True, True, True],
        [True, True, True]])


2.指定区间的张量创建

In [41]:
tensor1=torch.arange(10,30,2)
print(tensor1)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


In [42]:
tensor1=torch.arange(6)
print(tensor1)

tensor([0, 1, 2, 3, 4, 5])


In [ ]:
tensor1=torch.linspace(10,30,5)
print(tensor1)

In [43]:
tensor1=torch.logspace(1,3,3,2)
print(tensor1)

tensor([2., 4., 8.])


3.按数值填充张量

In [45]:
tensor1=torch.zeros(2,3)
print(tensor1)
print(tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [47]:
tensor2=torch.ones_like(tensor1)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [52]:
torch1=torch.full((3,2),6)
print(torch1)
print(torch1.dtype)

tensor([[6, 6],
        [6, 6],
        [6, 6]])
torch.int64


In [53]:
tensor2=torch.empty_like(tensor1)
print(tensor2)

tensor([[-6.0103e-31,  1.9730e-42,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00]])


In [55]:
tensor1=torch.eye(3)
print(tensor1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32


In [57]:
tensor1=torch.eye(3,5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


4.随机张量创建

In [58]:
tensor1=torch.rand(2,3)
print(tensor1)

tensor([[0.5303, 0.6981, 0.5309],
        [0.6615, 0.6908, 0.5022]])


In [59]:
tensor2=torch.rand_like(tensor1)
print(tensor2)

tensor([[0.0981, 0.0396, 0.4394],
        [0.6998, 0.0551, 0.1218]])


In [60]:
tensor1=torch.randint(low=0,high=100,size=(2,3))
print(tensor1)

tensor([[36, 71, 95],
        [40, 38, 39]])


In [67]:
tensor2=torch.randint_like(tensor1,low=10,high=20)
print(tensor2)

tensor([[18, 18, 16],
        [14, 18, 18]])
torch.int64


In [70]:
tensor1=torch.randn(4,2)
print(tensor1)

tensor([[-1.7194, -1.0794],
        [ 0.9647,  1.4830],
        [-1.4035,  0.3368],
        [ 1.1471,  0.0904]])


In [71]:
tensor2=torch.randn_like(tensor1)
print(tensor2)

tensor([[-0.7872, -0.1011],
        [ 1.3668, -0.4774],
        [ 0.5990,  1.1596],
        [ 0.0444,  0.7325]])


In [72]:
tensor1=torch.normal(5,2,tensor2.shape)
print(tensor1)

tensor([[4.9882, 6.1266],
        [4.1600, 8.0298],
        [5.8638, 4.9631],
        [5.0926, 7.5073]])


In [73]:
#随即重新排列
tensor1=torch.randperm(10)
print(tensor1)

tensor([1, 6, 8, 2, 4, 9, 5, 0, 3, 7])


In [74]:
#查看和指定随机数种子
print(torch.random.initial_seed())

175069488715900


In [75]:
torch.random.manual_seed(42)

In [77]:
print(torch.random.initial_seed())

42
