In [1]:
import torch

In [8]:
tensor1=torch.randint(1,10,(3,2,4)).float()
print(tensor1)

tensor([[[1., 7., 7., 9.],
         [2., 9., 8., 7.]],

        [[7., 2., 1., 5.],
         [3., 2., 6., 9.]],

        [[7., 2., 5., 3.],
         [8., 9., 3., 2.]]])


In [9]:
#sum求和
print(tensor1.sum())

tensor(124.)


In [10]:
print(tensor1.sum(dim=2))

tensor([[24., 26.],
        [15., 20.],
        [17., 22.]])


In [12]:
#mean求均值
print(tensor1.mean(dim=2))

tensor([[6.0000, 6.5000],
        [3.7500, 5.0000],
        [4.2500, 5.5000]])


In [13]:
#求标准方差
print(tensor1.std())

tensor(2.8842)


In [15]:
# max,min求最大最小值
print(tensor1.min( dim=2))


torch.return_types.min(
values=tensor([[1., 2.],
        [1., 2.],
        [2., 2.]]),
indices=tensor([[0, 0],
        [2, 1],
        [1, 3]]))


In [17]:
print(tensor1.argmin())

tensor(0)


In [18]:
print(tensor1.argmax())

tensor(3)


In [22]:
print(tensor1.unique())

tensor([1., 2., 3., 5., 6., 7., 8., 9.])


In [23]:
print(tensor1.sort(dim=2))

torch.return_types.sort(
values=tensor([[[1., 7., 7., 9.],
         [2., 7., 8., 9.]],

        [[1., 2., 5., 7.],
         [2., 3., 6., 9.]],

        [[2., 3., 5., 7.],
         [2., 3., 8., 9.]]]),
indices=tensor([[[0, 1, 2, 3],
         [0, 3, 2, 1]],

        [[2, 1, 3, 0],
         [1, 0, 2, 3]],

        [[1, 3, 2, 0],
         [3, 2, 0, 1]]]))
