In [1]:
import torch

In [15]:
x=torch.tensor(2.0,requires_grad=True)
y=x.detach()
print(x)
print(y)

tensor(2., requires_grad=True)
tensor(2.)


In [4]:
print(x.requires_grad)
print(y.requires_grad)

True
False


In [5]:
print(id(x))
print(id(y))

1703101074080
1703101076480


In [12]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

4712170524992
4712170524992


In [13]:
# print(x)
# y.zero_()
# print(x)

tensor(2., requires_grad=True)
tensor(0., requires_grad=True)


In [16]:
# 分别对x和y进行后续计算
z1=x**2
z2=y**2
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [17]:
print(z1.requires_grad)
print(z2.requires_grad)

True
False


In [18]:
z1.sum().backward()

In [20]:
# z2.sum().backward()

In [22]:
x=torch.ones(2,2,requires_grad=True)
y=x**x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward1>)


In [23]:
# 分离y
u=y.detach()
print(u)

tensor([[1., 1.],
        [1., 1.]])


In [24]:
#让u参与张量的计算
Z=u*x
print(Z)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [25]:
#反向传播，计算所有梯度
Z.sum().backward()

In [26]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [28]:
print(x.grad==u)

tensor([[True, True],
        [True, True]])
