In [4]:
import torch

In [2]:
tensor1=torch.randint(1,10,(2,3,6))
print(tensor1)

tensor([[[4, 3, 3, 2, 3, 3],
         [9, 6, 6, 7, 8, 5],
         [4, 1, 8, 1, 6, 6]],

        [[2, 7, 3, 4, 5, 3],
         [7, 5, 5, 1, 1, 8],
         [9, 2, 2, 1, 4, 6]]])


In [4]:
#交换两个维度
print(tensor1.transpose(0,2))

tensor([[[4, 2],
         [9, 7],
         [4, 9]],

        [[3, 7],
         [6, 5],
         [1, 2]],

        [[3, 3],
         [6, 5],
         [8, 2]],

        [[2, 4],
         [7, 1],
         [1, 1]],

        [[3, 5],
         [8, 1],
         [6, 4]],

        [[3, 3],
         [5, 8],
         [6, 6]]])


In [ ]:
#重新排列多个维度
print(tensor1.permute(0,2,1))

调整形状

In [8]:
tensor1=torch.randint(1,10,(3,5,4))
print(tensor1.shape)
print(tensor1)

torch.Size([3, 5, 4])
tensor([[[7, 8, 1, 5],
         [2, 1, 5, 2],
         [8, 6, 4, 3],
         [8, 8, 8, 1],
         [4, 7, 5, 4]],

        [[6, 7, 2, 5],
         [2, 9, 6, 4],
         [5, 5, 1, 9],
         [9, 9, 2, 2],
         [4, 1, 5, 5]],

        [[9, 9, 7, 7],
         [7, 2, 6, 7],
         [4, 6, 1, 2],
         [7, 1, 8, 5],
         [8, 7, 2, 9]]])


In [10]:
#1.reshape
print(tensor1.reshape(3,-1))

tensor([[7, 8, 1, 5, 2, 1, 5, 2, 8, 6, 4, 3, 8, 8, 8, 1, 4, 7, 5, 4],
        [6, 7, 2, 5, 2, 9, 6, 4, 5, 5, 1, 9, 9, 9, 2, 2, 4, 1, 5, 5],
        [9, 9, 7, 7, 7, 2, 6, 7, 4, 6, 1, 2, 7, 1, 8, 5, 8, 7, 2, 9]])


In [11]:
print(tensor1.reshape(-1))

tensor([7, 8, 1, 5, 2, 1, 5, 2, 8, 6, 4, 3, 8, 8, 8, 1, 4, 7, 5, 4, 6, 7, 2, 5,
        2, 9, 6, 4, 5, 5, 1, 9, 9, 9, 2, 2, 4, 1, 5, 5, 9, 9, 7, 7, 7, 2, 6, 7,
        4, 6, 1, 2, 7, 1, 8, 5, 8, 7, 2, 9])


In [12]:
#2.view
print(tensor1.is_contiguous())

True


In [13]:
print(tensor1.view(-1,10))

tensor([[7, 8, 1, 5, 2, 1, 5, 2, 8, 6],
        [4, 3, 8, 8, 8, 1, 4, 7, 5, 4],
        [6, 7, 2, 5, 2, 9, 6, 4, 5, 5],
        [1, 9, 9, 9, 2, 2, 4, 1, 5, 5],
        [9, 9, 7, 7, 7, 2, 6, 7, 4, 6],
        [1, 2, 7, 1, 8, 5, 8, 7, 2, 9]])


In [14]:
print(tensor1.shape)

torch.Size([3, 5, 4])


In [20]:
#对张量进行转置操作，让内存空间不连续
tensor1=tensor1.permute(2,1,0)
print(tensor1.shape)

torch.Size([4, 5, 3])


In [21]:
print(tensor1.is_contiguous())

False


In [22]:
print(tensor1.contiguous().view(-1,10))

tensor([[7, 6, 9, 2, 2, 7, 8, 5, 4, 8],
        [9, 7, 4, 4, 8, 8, 7, 9, 1, 9],
        [2, 6, 5, 6, 8, 9, 1, 7, 1, 7],
        [1, 2, 7, 5, 6, 6, 4, 1, 1, 8],
        [2, 8, 5, 5, 2, 5, 5, 7, 2, 4],
        [7, 3, 9, 2, 1, 2, 5, 4, 5, 9]])


In [5]:
#1.增加或删除维度
tensor1=torch.tensor([1,2,3])
print(tensor1)

tensor([1, 2, 3])


In [6]:
#在0维上增加一个维度，1×3
print(tensor1.unsqueeze(dim=0))

tensor([[1, 2, 3]])


In [7]:
#在1维上增加一个维度，3×1
print(tensor1.unsqueeze(dim=1))

tensor([[1],
        [2],
        [3]])


In [10]:
print(tensor1.unsqueeze(dim=-1))
print(tensor1)

tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])


In [11]:
print(tensor1.unsqueeze_(dim=-2))
print(tensor1)

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [12]:
#2.减少维度
print(tensor1.squeeze(dim=0))

tensor([1, 2, 3])


张量拼接操作

In [13]:
#1.拼接
tensor1=torch.randint(1,10,(2,2,5))
tensor2=torch.randint(1,10,(2,3,5))
print(tensor1)
print(tensor2)

tensor([[[1, 4, 5, 1, 2],
         [6, 2, 7, 9, 2]],

        [[6, 8, 4, 5, 4],
         [8, 9, 5, 1, 8]]])
tensor([[[3, 6, 9, 3, 9],
         [2, 2, 1, 1, 6],
         [2, 4, 5, 1, 5]],

        [[6, 3, 2, 3, 6],
         [7, 1, 8, 9, 2],
         [1, 6, 6, 6, 2]]])


In [14]:
print(torch.cat((tensor1,tensor2),dim=1))

tensor([[[1, 4, 5, 1, 2],
         [6, 2, 7, 9, 2],
         [3, 6, 9, 3, 9],
         [2, 2, 1, 1, 6],
         [2, 4, 5, 1, 5]],

        [[6, 8, 4, 5, 4],
         [8, 9, 5, 1, 8],
         [6, 3, 2, 3, 6],
         [7, 1, 8, 9, 2],
         [1, 6, 6, 6, 2]]])


In [15]:
#2.堆叠
tensor1=torch.randint(1,10,(4,3,5))
tensor2=torch.randint(1,10,(4,3,5))
print(tensor1)
print(tensor2)

tensor([[[8, 2, 3, 7, 1],
         [8, 8, 3, 6, 4],
         [5, 7, 2, 7, 4]],

        [[9, 8, 7, 8, 5],
         [5, 4, 4, 2, 3],
         [8, 7, 5, 9, 5]],

        [[7, 3, 1, 9, 8],
         [5, 5, 8, 3, 9],
         [7, 6, 9, 7, 9]],

        [[3, 1, 8, 9, 6],
         [8, 7, 9, 9, 6],
         [7, 8, 9, 7, 8]]])
tensor([[[2, 8, 3, 2, 4],
         [7, 3, 7, 4, 2],
         [1, 5, 6, 6, 3]],

        [[8, 9, 6, 6, 7],
         [7, 1, 2, 9, 1],
         [2, 1, 4, 8, 6]],

        [[3, 6, 9, 8, 9],
         [7, 4, 2, 9, 1],
         [3, 6, 4, 2, 3]],

        [[6, 4, 1, 4, 9],
         [9, 5, 6, 3, 6],
         [8, 3, 3, 8, 8]]])


In [17]:
tensor3=torch.stack([tensor1,tensor2],dim=0)
print(tensor3.shape)

torch.Size([2, 4, 3, 5])


In [22]:
tensor3=torch.stack([tensor1,tensor2],dim=1)
print(tensor3.shape)
print(tensor3)

torch.Size([4, 2, 3, 5])
tensor([[[[8, 2, 3, 7, 1],
          [8, 8, 3, 6, 4],
          [5, 7, 2, 7, 4]],

         [[2, 8, 3, 2, 4],
          [7, 3, 7, 4, 2],
          [1, 5, 6, 6, 3]]],


        [[[9, 8, 7, 8, 5],
          [5, 4, 4, 2, 3],
          [8, 7, 5, 9, 5]],

         [[8, 9, 6, 6, 7],
          [7, 1, 2, 9, 1],
          [2, 1, 4, 8, 6]]],


        [[[7, 3, 1, 9, 8],
          [5, 5, 8, 3, 9],
          [7, 6, 9, 7, 9]],

         [[3, 6, 9, 8, 9],
          [7, 4, 2, 9, 1],
          [3, 6, 4, 2, 3]]],


        [[[3, 1, 8, 9, 6],
          [8, 7, 9, 9, 6],
          [7, 8, 9, 7, 8]],

         [[6, 4, 1, 4, 9],
          [9, 5, 6, 3, 6],
          [8, 3, 3, 8, 8]]]])


In [21]:
tensor3=torch.stack([tensor1,tensor2],dim=2)
print(tensor3.shape)

torch.Size([4, 3, 2, 5])
