In [1]:
import torch

In [4]:
tensor1=torch.randint(1,10,(3,5,4))
print(tensor1)


tensor([[[4, 2, 7, 4],
         [4, 4, 9, 7],
         [4, 3, 4, 6],
         [9, 3, 3, 8],
         [2, 1, 5, 7]],

        [[7, 4, 4, 2],
         [4, 6, 8, 2],
         [2, 3, 2, 3],
         [5, 3, 3, 7],
         [9, 3, 4, 5]],

        [[2, 9, 1, 2],
         [6, 9, 1, 9],
         [2, 4, 1, 1],
         [1, 3, 3, 3],
         [9, 4, 9, 6]]])


In [9]:
# 1.简单索引
print(tensor1[2,1,3])
print(tensor1[2][1][3])

tensor(9)
tensor(9)


In [8]:
print(tensor1[2,3])
print(tensor1[2][3])

tensor([1, 3, 3, 3])
tensor([1, 3, 3, 3])


In [7]:
print(tensor1[1])

tensor([[7, 4, 4, 2],
        [4, 6, 8, 2],
        [2, 3, 2, 3],
        [5, 3, 3, 7],
        [9, 3, 4, 5]])


In [10]:
print(tensor1[:,3])

tensor([[9, 3, 3, 8],
        [5, 3, 3, 7],
        [1, 3, 3, 3]])


In [11]:
# 2.范围索引
print(tensor1[1:])

tensor([[[7, 4, 4, 2],
         [4, 6, 8, 2],
         [2, 3, 2, 3],
         [5, 3, 3, 7],
         [9, 3, 4, 5]],

        [[2, 9, 1, 2],
         [6, 9, 1, 9],
         [2, 4, 1, 1],
         [1, 3, 3, 3],
         [9, 4, 9, 6]]])


In [19]:
print(tensor1[-1:,1:4:2,0:3:2])

tensor([[[6, 1],
         [1, 3]]])


In [20]:
print(tensor1[-1:,-4:-1:2,0:3:2])

tensor([[[6, 1],
         [1, 3]]])


In [21]:
#列表索引
print(tensor1[[0,1],[1,2]]) #第0矩阵的第1行，第1矩阵的第2行

tensor([[4, 4, 9, 7],
        [2, 3, 2, 3]])


In [22]:
print(tensor1[[0,1],[3,2],[2,3]])

tensor([3, 3])


In [29]:
print(tensor1[[[0],[1]],[1,2]])

tensor([[[4, 4, 9, 7],
         [4, 3, 4, 6]],

        [[4, 6, 8, 2],
         [2, 3, 2, 3]]])


In [30]:
#布尔索引
#选取符合条件的行，首元素大于5
mask=tensor1[:,:,0]>5
print(mask)

tensor([[False, False, False,  True, False],
        [ True, False, False, False,  True],
        [False,  True, False, False,  True]])


In [31]:
print(tensor1[mask])

tensor([[9, 3, 3, 8],
        [7, 4, 4, 2],
        [9, 3, 4, 5],
        [6, 9, 1, 9],
        [9, 4, 9, 6]])


In [33]:
#选取符合条件的行，第二个元素大于5
mask=tensor1[:,1,:]>5
print(mask)


tensor([[False, False,  True,  True],
        [False,  True,  True, False],
        [ True,  True, False,  True]])


In [35]:
# print(tensor1[mask])
tensor2=tensor1.mT
print(tensor2)

tensor([[[4, 4, 4, 9, 2],
         [2, 4, 3, 3, 1],
         [7, 9, 4, 3, 5],
         [4, 7, 6, 8, 7]],

        [[7, 4, 2, 5, 9],
         [4, 6, 3, 3, 3],
         [4, 8, 2, 3, 4],
         [2, 2, 3, 7, 5]],

        [[2, 6, 2, 1, 9],
         [9, 9, 4, 3, 4],
         [1, 1, 1, 3, 9],
         [2, 9, 1, 3, 6]]])


In [42]:
#将mask运用到tensor2上，形状匹配前两个维度
print(tensor2[mask])

tensor([[7, 9, 4, 3, 5],
        [4, 7, 6, 8, 7],
        [4, 6, 3, 3, 3],
        [4, 8, 2, 3, 4],
        [2, 6, 2, 1, 9],
        [9, 9, 4, 3, 4],
        [2, 9, 1, 3, 6]])


In [46]:
print(tensor2[mask].mT)
print(tensor2[mask].T)

tensor([[7, 4, 4, 4, 2, 9, 2],
        [9, 7, 6, 8, 6, 9, 9],
        [4, 6, 3, 2, 2, 4, 1],
        [3, 8, 3, 3, 1, 3, 3],
        [5, 7, 3, 4, 9, 4, 6]])
tensor([[7, 4, 4, 4, 2, 9, 2],
        [9, 7, 6, 8, 6, 9, 9],
        [4, 6, 3, 2, 2, 4, 1],
        [3, 8, 3, 3, 1, 3, 3],
        [5, 7, 3, 4, 9, 4, 6]])


In [48]:
#选取符合条件的矩阵，元素(1,2)>5
mask=tensor1[:,1,2]>5
print(mask)
print(tensor1[mask])

tensor([ True,  True, False])
tensor([[[4, 2, 7, 4],
         [4, 4, 9, 7],
         [4, 3, 4, 6],
         [9, 3, 3, 8],
         [2, 1, 5, 7]],

        [[7, 4, 4, 2],
         [4, 6, 8, 2],
         [2, 3, 2, 3],
         [5, 3, 3, 7],
         [9, 3, 4, 5]]])


In [51]:
mask=tensor1>5
print(mask)


tensor([[[False, False,  True, False],
         [False, False,  True,  True],
         [False, False, False,  True],
         [ True, False, False,  True],
         [False, False, False,  True]],

        [[ True, False, False, False],
         [False,  True,  True, False],
         [False, False, False, False],
         [False, False, False,  True],
         [ True, False, False, False]],

        [[False,  True, False, False],
         [ True,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False],
         [ True, False,  True,  True]]])


In [50]:
print(tensor1[mask])

tensor([7, 9, 7, 6, 9, 8, 7, 7, 6, 8, 7, 9, 9, 6, 9, 9, 9, 9, 6])


TypeError: permute(): argument 'input' (position 1) must be Tensor, not int