In [1]:
import torch
import torch.nn as nn

In [4]:
# 1.目标值为顺序编码的标签
input=torch.randn(6,8)
print(input)
# pred=torch.softmax(input,dim=1)
# print(pred)

tensor([[ 0.0182,  0.2038,  1.1706,  0.9031,  0.3581, -0.0218,  0.1239,  0.4856],
        [ 0.0419, -0.9955,  0.4334,  0.1864,  0.1518,  0.8247,  0.1443,  1.5253],
        [-0.5740, -1.6114, -0.7111, -0.9631, -1.9229, -0.5399,  0.9726, -0.6762],
        [ 1.0747, -0.5292,  0.3545, -1.2425, -0.9686, -0.4388,  0.8380, -0.4607],
        [-0.2823,  0.2086,  1.9114, -1.0223,  0.5478, -0.5751,  0.4674, -0.7049],
        [-1.2777,  0.7450, -1.0775,  0.9876,  0.0894, -0.1062,  0.6046,  0.6778]])
tensor([[0.0777, 0.0936, 0.2461, 0.1883, 0.1092, 0.0747, 0.0864, 0.1240],
        [0.0781, 0.0277, 0.1155, 0.0902, 0.0871, 0.1708, 0.0865, 0.3441],
        [0.1021, 0.0362, 0.0890, 0.0692, 0.0265, 0.1056, 0.4793, 0.0922],
        [0.3184, 0.0640, 0.1549, 0.0314, 0.0413, 0.0701, 0.2513, 0.0686],
        [0.0559, 0.0913, 0.5013, 0.0267, 0.1282, 0.0417, 0.1183, 0.0366],
        [0.0249, 0.1880, 0.0304, 0.2397, 0.0976, 0.0803, 0.1634, 0.1758]])


In [3]:
# 目标值，6个数据的类别标签（0~7）
target=torch.tensor([1,0,3,7,5,2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [10]:
# 定义损失函数
loss=nn.CrossEntropyLoss()
print(loss(input,target))

tensor(2.8235)


In [11]:
# 2.目标值为一组概率
input=torch.randn(6,8)
print(input)

tensor([[ 0.8570, -1.7688, -0.1833,  0.8405, -0.8855, -1.2484,  0.0839,  1.6131],
        [ 0.4313,  0.3145, -1.4293, -2.5694,  0.0043,  1.7697,  1.4876, -0.8806],
        [ 0.9395, -0.2377, -0.2392, -0.8929,  1.0623, -0.5712,  1.1887,  0.2259],
        [-0.1007,  0.8984,  0.5441,  0.7629, -0.3088, -2.0612, -0.5223,  0.6824],
        [-1.3074, -0.5471, -0.5628,  1.2959, -0.0047,  0.4147, -0.0820, -0.1022],
        [ 2.2658,  0.7518,  1.2253,  0.2085, -0.9091, -0.4046, -0.7172, -0.8214]])


In [12]:
target=torch.randn(6,8).softmax(dim=1)
print(target)

tensor([[0.0279, 0.2194, 0.0547, 0.3203, 0.0474, 0.2154, 0.0926, 0.0223],
        [0.0241, 0.3304, 0.0137, 0.0574, 0.0430, 0.0206, 0.0096, 0.5011],
        [0.4619, 0.0416, 0.1707, 0.1847, 0.0380, 0.0110, 0.0643, 0.0277],
        [0.0431, 0.0208, 0.1200, 0.0449, 0.0583, 0.2085, 0.3290, 0.1754],
        [0.3197, 0.1253, 0.1170, 0.0679, 0.0560, 0.0804, 0.2115, 0.0223],
        [0.0371, 0.1496, 0.2060, 0.1215, 0.1383, 0.1593, 0.0944, 0.0939]])


In [13]:
loss=nn.CrossEntropyLoss()
print(loss(input,target))

tensor(2.7425)
