In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个全连接层
linear=nn.Linear(5,2)

In [5]:
# 1.常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [6]:
nn.init.ones_(linear.bias)
print(linear.bias)

Parameter containing:
tensor([1., 1.], requires_grad=True)


In [7]:
nn.init.constant_(linear.weight,10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [8]:
# 2.秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [10]:
# 3.正态分布初始化
nn.init.normal_(linear.weight,mean=0,std=0.1)
print(linear.weight)

Parameter containing:
tensor([[-0.1744, -0.0900, -0.0407,  0.0172,  0.0187],
        [-0.0154, -0.0637,  0.0092,  0.0650, -0.0520]], requires_grad=True)


In [11]:
# 4.均匀分布初始化
nn.init.uniform_(linear.weight,a=-3.0,b=3.0)
print(linear.weight)

Parameter containing:
tensor([[ 2.5551,  2.5242,  2.3911, -0.1635,  1.5853],
        [-0.8129,  0.2113, -0.9850,  0.2785, -0.5084]], requires_grad=True)


In [12]:
# 5.Xavier初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.4274,  0.4136,  0.5327, -0.4194,  0.0700],
        [ 0.1125, -0.9584,  0.0051, -0.0546,  0.3913]], requires_grad=True)


In [13]:
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.5239, -0.8967,  0.4039, -0.5133, -0.8873],
        [ 0.0490,  0.0947, -0.7333,  0.3363, -0.5234]], requires_grad=True)


In [14]:
# 6.He初始化
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.7670, -0.5597, -0.1715,  0.4675, -0.6445],
        [ 0.5124, -0.7547,  1.1782, -0.2683, -0.8375]], requires_grad=True)


In [15]:
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-1.0010, -0.7612,  1.0432, -0.1792, -0.7162],
        [-0.1339,  0.3220,  0.5943, -0.5340,  0.4071]], requires_grad=True)


In [19]:
input=torch.randn(1,5,device='cuda')
print(input.device)

cuda:0


In [21]:
input=torch.tensor([[1,2,3],[4,5,6]],device='cpu').to(device='cuda')
print(input.device)

cuda:0
