In [1]:
import torch
import torch.nn as nn

In [7]:
# 输入数据
input=torch.randn(3,2)
print(input)
# 得到预测概率值
pred=torch.sigmoid(input)
print(pred)

tensor([[ 0.3217,  1.9709],
        [ 0.3401,  0.6496],
        [-1.0543, -1.2520]])
tensor([[0.5797, 0.8777],
        [0.5842, 0.6569],
        [0.2584, 0.2224]])


In [8]:
# 目标值
target=torch.tensor([[0,1],[1,0],[0,1]],dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [9]:
# 定义损失函数
loss=nn.BCELoss()
print(loss(pred,target))

tensor(0.7345)
