In [1]:
import torch
import torch.nn as nn

In [2]:
# 定义RNN层
rnn=nn.RNN(input_size=8,hidden_size=16,num_layers=2)

In [3]:
# 定义输入数据和初始隐状态
input=torch.randn(1,3,8)
hx=torch.randn(2,3,16)
print(input)
print(hx)

tensor([[[ 0.2221,  0.3648,  0.5367,  0.3189, -1.3593, -0.8118,  0.3823,
           0.8679],
         [-1.9517, -1.2553,  1.0251, -1.0699,  1.4191,  0.1317,  0.5897,
          -0.5114],
         [-0.9263,  0.4724,  0.3816,  0.1043, -1.4077, -0.1882,  0.3053,
          -0.2167]]])
tensor([[[-1.1359,  0.8398,  1.9557,  2.1694,  1.4507, -0.2271, -0.5900,
          -0.9287,  2.2082, -0.8380, -0.9774, -0.7308, -0.9495,  0.9518,
          -1.2338,  0.7694],
         [-1.3743,  0.7137,  0.1184,  0.2053,  0.8485, -0.5975,  0.1911,
           1.2328, -0.5423,  0.2885,  1.3585,  0.8093, -0.3866,  0.4828,
          -0.1691,  0.3604],
         [ 0.3611,  0.1066, -0.0065, -0.7494,  0.1674, -0.9536,  0.9781,
          -0.1251, -0.4169,  0.0056,  0.9652,  0.5002, -1.6097,  0.2045,
           0.1012, -1.2613]],

        [[ 0.7219,  0.6898, -1.5185,  0.7837,  0.7009,  1.3693,  0.4285,
          -0.1482, -1.3168,  0.7896, -2.4220,  0.0137, -1.0843,  1.3828,
          -0.2245, -0.7253],
         [ 0.3726

In [5]:
# 前向传播，得到输出和隐状态
output,nn=rnn(input,hx)
print(output)
print(nn)
print(output.shape)
print(nn.shape)

tensor([[[ 0.1968,  0.4252,  0.3662,  0.9120,  0.4031, -0.3702,  0.6896,
          -0.6219,  0.3040,  0.4162,  0.8891, -0.5002,  0.6909,  0.4989,
           0.7183,  0.1558],
         [ 0.2771,  0.4032,  0.5584, -0.2628,  0.1101, -0.7938,  0.2302,
           0.6608, -0.7828, -0.3903,  0.2734, -0.4162,  0.8479, -0.7043,
           0.8628,  0.0914],
         [ 0.7173,  0.2940,  0.2682,  0.4478, -0.4565,  0.1538, -0.5099,
          -0.6174,  0.1257,  0.5009, -0.1638, -0.7547,  0.7885, -0.4120,
           0.4186,  0.1538]]], grad_fn=<StackBackward0>)
tensor([[[-0.1021,  0.5398,  0.4130,  0.1805,  0.1150,  0.5303,  0.6441,
           0.6524, -0.7457,  0.7036,  0.2325,  0.6589, -0.9244, -0.9197,
           0.3352, -0.1486],
         [ 0.3689, -0.8595,  0.2618, -0.0428, -0.1046, -0.7508,  0.4894,
          -0.5320,  0.5251, -0.0138,  0.1422,  0.0664,  0.5570, -0.5182,
          -0.7790,  0.0540],
         [ 0.3342, -0.5557,  0.2694,  0.5844,  0.6236,  0.1055,  0.3769,
          -0.5233, -0.53